// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210703095722_ActualizandoRegistros2")]
    partial class ActualizandoRegistros2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Descripcion = "Description for product 1",
                            Nombre = "Product 1",
                            Precio = 238m
                        },
                        new
                        {
                            ProductId = 2,
                            Descripcion = "Description for product 2",
                            Nombre = "Product 2",
                            Precio = 612m
                        },
                        new
                        {
                            ProductId = 3,
                            Descripcion = "Description for product 3",
                            Nombre = "Product 3",
                            Precio = 304m
                        },
                        new
                        {
                            ProductId = 4,
                            Descripcion = "Description for product 4",
                            Nombre = "Product 4",
                            Precio = 287m
                        },
                        new
                        {
                            ProductId = 5,
                            Descripcion = "Description for product 5",
                            Nombre = "Product 5",
                            Precio = 385m
                        },
                        new
                        {
                            ProductId = 6,
                            Descripcion = "Description for product 6",
                            Nombre = "Product 6",
                            Precio = 337m
                        },
                        new
                        {
                            ProductId = 7,
                            Descripcion = "Description for product 7",
                            Nombre = "Product 7",
                            Precio = 395m
                        },
                        new
                        {
                            ProductId = 8,
                            Descripcion = "Description for product 8",
                            Nombre = "Product 8",
                            Precio = 405m
                        },
                        new
                        {
                            ProductId = 9,
                            Descripcion = "Description for product 9",
                            Nombre = "Product 9",
                            Precio = 244m
                        },
                        new
                        {
                            ProductId = 10,
                            Descripcion = "Description for product 10",
                            Nombre = "Product 10",
                            Precio = 108m
                        },
                        new
                        {
                            ProductId = 11,
                            Descripcion = "Description for product 11",
                            Nombre = "Product 11",
                            Precio = 114m
                        },
                        new
                        {
                            ProductId = 12,
                            Descripcion = "Description for product 12",
                            Nombre = "Product 12",
                            Precio = 921m
                        },
                        new
                        {
                            ProductId = 13,
                            Descripcion = "Description for product 13",
                            Nombre = "Product 13",
                            Precio = 517m
                        },
                        new
                        {
                            ProductId = 14,
                            Descripcion = "Description for product 14",
                            Nombre = "Product 14",
                            Precio = 713m
                        },
                        new
                        {
                            ProductId = 15,
                            Descripcion = "Description for product 15",
                            Nombre = "Product 15",
                            Precio = 686m
                        },
                        new
                        {
                            ProductId = 16,
                            Descripcion = "Description for product 16",
                            Nombre = "Product 16",
                            Precio = 694m
                        },
                        new
                        {
                            ProductId = 17,
                            Descripcion = "Description for product 17",
                            Nombre = "Product 17",
                            Precio = 727m
                        },
                        new
                        {
                            ProductId = 18,
                            Descripcion = "Description for product 18",
                            Nombre = "Product 18",
                            Precio = 552m
                        },
                        new
                        {
                            ProductId = 19,
                            Descripcion = "Description for product 19",
                            Nombre = "Product 19",
                            Precio = 401m
                        },
                        new
                        {
                            ProductId = 20,
                            Descripcion = "Description for product 20",
                            Nombre = "Product 20",
                            Precio = 138m
                        },
                        new
                        {
                            ProductId = 21,
                            Descripcion = "Description for product 21",
                            Nombre = "Product 21",
                            Precio = 530m
                        },
                        new
                        {
                            ProductId = 22,
                            Descripcion = "Description for product 22",
                            Nombre = "Product 22",
                            Precio = 767m
                        },
                        new
                        {
                            ProductId = 23,
                            Descripcion = "Description for product 23",
                            Nombre = "Product 23",
                            Precio = 620m
                        },
                        new
                        {
                            ProductId = 24,
                            Descripcion = "Description for product 24",
                            Nombre = "Product 24",
                            Precio = 963m
                        },
                        new
                        {
                            ProductId = 25,
                            Descripcion = "Description for product 25",
                            Nombre = "Product 25",
                            Precio = 416m
                        },
                        new
                        {
                            ProductId = 26,
                            Descripcion = "Description for product 26",
                            Nombre = "Product 26",
                            Precio = 831m
                        },
                        new
                        {
                            ProductId = 27,
                            Descripcion = "Description for product 27",
                            Nombre = "Product 27",
                            Precio = 579m
                        },
                        new
                        {
                            ProductId = 28,
                            Descripcion = "Description for product 28",
                            Nombre = "Product 28",
                            Precio = 739m
                        },
                        new
                        {
                            ProductId = 29,
                            Descripcion = "Description for product 29",
                            Nombre = "Product 29",
                            Precio = 739m
                        },
                        new
                        {
                            ProductId = 30,
                            Descripcion = "Description for product 30",
                            Nombre = "Product 30",
                            Precio = 753m
                        },
                        new
                        {
                            ProductId = 31,
                            Descripcion = "Description for product 31",
                            Nombre = "Product 31",
                            Precio = 118m
                        },
                        new
                        {
                            ProductId = 32,
                            Descripcion = "Description for product 32",
                            Nombre = "Product 32",
                            Precio = 358m
                        },
                        new
                        {
                            ProductId = 33,
                            Descripcion = "Description for product 33",
                            Nombre = "Product 33",
                            Precio = 922m
                        },
                        new
                        {
                            ProductId = 34,
                            Descripcion = "Description for product 34",
                            Nombre = "Product 34",
                            Precio = 253m
                        },
                        new
                        {
                            ProductId = 35,
                            Descripcion = "Description for product 35",
                            Nombre = "Product 35",
                            Precio = 880m
                        },
                        new
                        {
                            ProductId = 36,
                            Descripcion = "Description for product 36",
                            Nombre = "Product 36",
                            Precio = 323m
                        },
                        new
                        {
                            ProductId = 37,
                            Descripcion = "Description for product 37",
                            Nombre = "Product 37",
                            Precio = 405m
                        },
                        new
                        {
                            ProductId = 38,
                            Descripcion = "Description for product 38",
                            Nombre = "Product 38",
                            Precio = 248m
                        },
                        new
                        {
                            ProductId = 39,
                            Descripcion = "Description for product 39",
                            Nombre = "Product 39",
                            Precio = 413m
                        },
                        new
                        {
                            ProductId = 40,
                            Descripcion = "Description for product 40",
                            Nombre = "Product 40",
                            Precio = 946m
                        },
                        new
                        {
                            ProductId = 41,
                            Descripcion = "Description for product 41",
                            Nombre = "Product 41",
                            Precio = 992m
                        },
                        new
                        {
                            ProductId = 42,
                            Descripcion = "Description for product 42",
                            Nombre = "Product 42",
                            Precio = 257m
                        },
                        new
                        {
                            ProductId = 43,
                            Descripcion = "Description for product 43",
                            Nombre = "Product 43",
                            Precio = 852m
                        },
                        new
                        {
                            ProductId = 44,
                            Descripcion = "Description for product 44",
                            Nombre = "Product 44",
                            Precio = 101m
                        },
                        new
                        {
                            ProductId = 45,
                            Descripcion = "Description for product 45",
                            Nombre = "Product 45",
                            Precio = 742m
                        },
                        new
                        {
                            ProductId = 46,
                            Descripcion = "Description for product 46",
                            Nombre = "Product 46",
                            Precio = 244m
                        },
                        new
                        {
                            ProductId = 47,
                            Descripcion = "Description for product 47",
                            Nombre = "Product 47",
                            Precio = 642m
                        },
                        new
                        {
                            ProductId = 48,
                            Descripcion = "Description for product 48",
                            Nombre = "Product 48",
                            Precio = 309m
                        },
                        new
                        {
                            ProductId = 49,
                            Descripcion = "Description for product 49",
                            Nombre = "Product 49",
                            Precio = 509m
                        },
                        new
                        {
                            ProductId = 50,
                            Descripcion = "Description for product 50",
                            Nombre = "Product 50",
                            Precio = 765m
                        },
                        new
                        {
                            ProductId = 51,
                            Descripcion = "Description for product 51",
                            Nombre = "Product 51",
                            Precio = 690m
                        },
                        new
                        {
                            ProductId = 52,
                            Descripcion = "Description for product 52",
                            Nombre = "Product 52",
                            Precio = 304m
                        },
                        new
                        {
                            ProductId = 53,
                            Descripcion = "Description for product 53",
                            Nombre = "Product 53",
                            Precio = 843m
                        },
                        new
                        {
                            ProductId = 54,
                            Descripcion = "Description for product 54",
                            Nombre = "Product 54",
                            Precio = 628m
                        },
                        new
                        {
                            ProductId = 55,
                            Descripcion = "Description for product 55",
                            Nombre = "Product 55",
                            Precio = 421m
                        },
                        new
                        {
                            ProductId = 56,
                            Descripcion = "Description for product 56",
                            Nombre = "Product 56",
                            Precio = 471m
                        },
                        new
                        {
                            ProductId = 57,
                            Descripcion = "Description for product 57",
                            Nombre = "Product 57",
                            Precio = 992m
                        },
                        new
                        {
                            ProductId = 58,
                            Descripcion = "Description for product 58",
                            Nombre = "Product 58",
                            Precio = 340m
                        },
                        new
                        {
                            ProductId = 59,
                            Descripcion = "Description for product 59",
                            Nombre = "Product 59",
                            Precio = 871m
                        },
                        new
                        {
                            ProductId = 60,
                            Descripcion = "Description for product 60",
                            Nombre = "Product 60",
                            Precio = 553m
                        },
                        new
                        {
                            ProductId = 61,
                            Descripcion = "Description for product 61",
                            Nombre = "Product 61",
                            Precio = 758m
                        },
                        new
                        {
                            ProductId = 62,
                            Descripcion = "Description for product 62",
                            Nombre = "Product 62",
                            Precio = 655m
                        },
                        new
                        {
                            ProductId = 63,
                            Descripcion = "Description for product 63",
                            Nombre = "Product 63",
                            Precio = 665m
                        },
                        new
                        {
                            ProductId = 64,
                            Descripcion = "Description for product 64",
                            Nombre = "Product 64",
                            Precio = 490m
                        },
                        new
                        {
                            ProductId = 65,
                            Descripcion = "Description for product 65",
                            Nombre = "Product 65",
                            Precio = 990m
                        },
                        new
                        {
                            ProductId = 66,
                            Descripcion = "Description for product 66",
                            Nombre = "Product 66",
                            Precio = 755m
                        },
                        new
                        {
                            ProductId = 67,
                            Descripcion = "Description for product 67",
                            Nombre = "Product 67",
                            Precio = 999m
                        },
                        new
                        {
                            ProductId = 68,
                            Descripcion = "Description for product 68",
                            Nombre = "Product 68",
                            Precio = 364m
                        },
                        new
                        {
                            ProductId = 69,
                            Descripcion = "Description for product 69",
                            Nombre = "Product 69",
                            Precio = 832m
                        },
                        new
                        {
                            ProductId = 70,
                            Descripcion = "Description for product 70",
                            Nombre = "Product 70",
                            Precio = 462m
                        },
                        new
                        {
                            ProductId = 71,
                            Descripcion = "Description for product 71",
                            Nombre = "Product 71",
                            Precio = 389m
                        },
                        new
                        {
                            ProductId = 72,
                            Descripcion = "Description for product 72",
                            Nombre = "Product 72",
                            Precio = 578m
                        },
                        new
                        {
                            ProductId = 73,
                            Descripcion = "Description for product 73",
                            Nombre = "Product 73",
                            Precio = 238m
                        },
                        new
                        {
                            ProductId = 74,
                            Descripcion = "Description for product 74",
                            Nombre = "Product 74",
                            Precio = 455m
                        },
                        new
                        {
                            ProductId = 75,
                            Descripcion = "Description for product 75",
                            Nombre = "Product 75",
                            Precio = 146m
                        },
                        new
                        {
                            ProductId = 76,
                            Descripcion = "Description for product 76",
                            Nombre = "Product 76",
                            Precio = 373m
                        },
                        new
                        {
                            ProductId = 77,
                            Descripcion = "Description for product 77",
                            Nombre = "Product 77",
                            Precio = 914m
                        },
                        new
                        {
                            ProductId = 78,
                            Descripcion = "Description for product 78",
                            Nombre = "Product 78",
                            Precio = 618m
                        },
                        new
                        {
                            ProductId = 79,
                            Descripcion = "Description for product 79",
                            Nombre = "Product 79",
                            Precio = 320m
                        },
                        new
                        {
                            ProductId = 80,
                            Descripcion = "Description for product 80",
                            Nombre = "Product 80",
                            Precio = 272m
                        },
                        new
                        {
                            ProductId = 81,
                            Descripcion = "Description for product 81",
                            Nombre = "Product 81",
                            Precio = 289m
                        },
                        new
                        {
                            ProductId = 82,
                            Descripcion = "Description for product 82",
                            Nombre = "Product 82",
                            Precio = 369m
                        },
                        new
                        {
                            ProductId = 83,
                            Descripcion = "Description for product 83",
                            Nombre = "Product 83",
                            Precio = 330m
                        },
                        new
                        {
                            ProductId = 84,
                            Descripcion = "Description for product 84",
                            Nombre = "Product 84",
                            Precio = 974m
                        },
                        new
                        {
                            ProductId = 85,
                            Descripcion = "Description for product 85",
                            Nombre = "Product 85",
                            Precio = 163m
                        },
                        new
                        {
                            ProductId = 86,
                            Descripcion = "Description for product 86",
                            Nombre = "Product 86",
                            Precio = 813m
                        },
                        new
                        {
                            ProductId = 87,
                            Descripcion = "Description for product 87",
                            Nombre = "Product 87",
                            Precio = 514m
                        },
                        new
                        {
                            ProductId = 88,
                            Descripcion = "Description for product 88",
                            Nombre = "Product 88",
                            Precio = 393m
                        },
                        new
                        {
                            ProductId = 89,
                            Descripcion = "Description for product 89",
                            Nombre = "Product 89",
                            Precio = 831m
                        },
                        new
                        {
                            ProductId = 90,
                            Descripcion = "Description for product 90",
                            Nombre = "Product 90",
                            Precio = 508m
                        },
                        new
                        {
                            ProductId = 91,
                            Descripcion = "Description for product 91",
                            Nombre = "Product 91",
                            Precio = 331m
                        },
                        new
                        {
                            ProductId = 92,
                            Descripcion = "Description for product 92",
                            Nombre = "Product 92",
                            Precio = 165m
                        },
                        new
                        {
                            ProductId = 93,
                            Descripcion = "Description for product 93",
                            Nombre = "Product 93",
                            Precio = 377m
                        },
                        new
                        {
                            ProductId = 94,
                            Descripcion = "Description for product 94",
                            Nombre = "Product 94",
                            Precio = 859m
                        },
                        new
                        {
                            ProductId = 95,
                            Descripcion = "Description for product 95",
                            Nombre = "Product 95",
                            Precio = 287m
                        },
                        new
                        {
                            ProductId = 96,
                            Descripcion = "Description for product 96",
                            Nombre = "Product 96",
                            Precio = 436m
                        },
                        new
                        {
                            ProductId = 97,
                            Descripcion = "Description for product 97",
                            Nombre = "Product 97",
                            Precio = 591m
                        },
                        new
                        {
                            ProductId = 98,
                            Descripcion = "Description for product 98",
                            Nombre = "Product 98",
                            Precio = 462m
                        },
                        new
                        {
                            ProductId = 99,
                            Descripcion = "Description for product 99",
                            Nombre = "Product 99",
                            Precio = 111m
                        },
                        new
                        {
                            ProductId = 100,
                            Descripcion = "Description for product 100",
                            Nombre = "Product 100",
                            Precio = 987m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
